// Generated by scripts/contract-snapshots.sh from sorocron_example_rebalance_resolver.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn target(env: soroban_sdk::Env) -> Target;
    fn set_target(env: soroban_sdk::Env, target: Target);
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(env: soroban_sdk::Env, admin: soroban_sdk::Address, target: Target);
    fn deviation_bps(env: soroban_sdk::Env) -> Option<i128>;
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Target {
    pub pair: soroban_sdk::Address,
    pub ratio: i128,
    pub threshold_bps: u32,
}

