// Generated by scripts/contract-snapshots.sh from sorocron_example_counter.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn count(env: soroban_sdk::Env) -> u32;
    fn increment(env: soroban_sdk::Env, by: u32) -> u32;
}

