// Generated by scripts/contract-snapshots.sh from sorocron_example_oracle_trigger.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn get_config(env: soroban_sdk::Env) -> TriggerConfig;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn update_price(env: soroban_sdk::Env, price: i128);
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        threshold_price: i128,
        trigger_below: bool,
    );
    fn set_threshold(env: soroban_sdk::Env, threshold_price: i128, trigger_below: bool);
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct TriggerConfig {
    pub active: bool,
    pub current_price: i128,
    pub threshold_price: i128,
    pub trigger_below: bool,
}

