// Generated by scripts/contract-snapshots.sh from sorocron_example_timelock_resolver.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn bind(
        env: soroban_sdk::Env,
        job_id: u64,
        proposal: soroban_sdk::BytesN<32>,
    ) -> Result<(), Error>;
    fn state(env: soroban_sdk::Env, proposal: soroban_sdk::BytesN<32>) -> ProposalState;
    fn register(
        env: soroban_sdk::Env,
        proposal: soroban_sdk::BytesN<32>,
        eta: u64,
        window: u64,
    ) -> Result<(), Error>;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(env: soroban_sdk::Env, admin: soroban_sdk::Address);
    fn mark_executed(
        env: soroban_sdk::Env,
        proposal: soroban_sdk::BytesN<32>,
    ) -> Result<(), Error>;
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum ProposalState {
    Unknown,
    Queued,
    Ready,
    Expired,
    Executed,
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    UnknownProposal = 1,
    AlreadyRegistered = 2,
}

