// Generated by scripts/contract-snapshots.sh from sorocron_example_subscription.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn plan(env: soroban_sdk::Env) -> Plan;
    fn cancel(env: soroban_sdk::Env, subscriber: soroban_sdk::Address);
    fn charge(
        env: soroban_sdk::Env,
        subscriber: soroban_sdk::Address,
    ) -> Result<u32, Error>;
    fn bind_job(env: soroban_sdk::Env, subscriber: soroban_sdk::Address, job_id: u64);
    fn subscribe(
        env: soroban_sdk::Env,
        subscriber: soroban_sdk::Address,
    ) -> Result<(), Error>;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn is_billable(env: soroban_sdk::Env, subscriber: soroban_sdk::Address) -> bool;
    fn subscription(
        env: soroban_sdk::Env,
        subscriber: soroban_sdk::Address,
    ) -> Option<Subscription>;
    fn __constructor(
        env: soroban_sdk::Env,
        merchant: soroban_sdk::Address,
        token: soroban_sdk::Address,
        price: i128,
        period: u64,
    );
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Plan {
    pub merchant: soroban_sdk::Address,
    pub period: u64,
    pub price: i128,
    pub token: soroban_sdk::Address,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Subscription {
    pub last_charged: Option<u64>,
    pub payments: u32,
    pub start: u64,
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    InvalidPlan = 1,
    NotSubscribed = 2,
    AlreadyCharged = 3,
    InsufficientAllowance = 4,
    AlreadySubscribed = 5,
}

