// Generated by scripts/contract-snapshots.sh from sorocron_example_limit_order.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn fill(env: soroban_sdk::Env) -> Result<i128, Error>;
    fn fund(env: soroban_sdk::Env) -> Result<(), Error>;
    fn order(env: soroban_sdk::Env) -> Order;
    fn quote(env: soroban_sdk::Env) -> i128;
    fn cancel(env: soroban_sdk::Env) -> Result<i128, Error>;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
        router: soroban_sdk::Address,
        sell_token: soroban_sdk::Address,
        buy_token: soroban_sdk::Address,
        amount_in: i128,
        min_amount_out: i128,
        expires_at: u64,
    );
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Order {
    pub amount_in: i128,
    pub buy_token: soroban_sdk::Address,
    pub expires_at: u64,
    pub filled_out: i128,
    pub funded: bool,
    pub min_amount_out: i128,
    pub open: bool,
    pub owner: soroban_sdk::Address,
    pub router: soroban_sdk::Address,
    pub sell_token: soroban_sdk::Address,
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    InvalidOrder = 1,
    NotFunded = 2,
    Closed = 3,
    Expired = 4,
    PriceNotReached = 5,
}

