// Generated by scripts/contract-snapshots.sh from sorocron_example_price_resolver.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn price(env: soroban_sdk::Env) -> Option<i128>;
    fn condition(env: soroban_sdk::Env) -> Condition;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        condition: Condition,
    );
    fn set_condition(env: soroban_sdk::Env, condition: Condition);
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Condition {
    pub asset: Asset,
    pub direction: Direction,
    pub max_age: u64,
    pub oracle: soroban_sdk::Address,
    pub threshold: i128,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Asset {
    Stellar(soroban_sdk::Address),
    Other(soroban_sdk::Symbol),
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Direction {
    Above,
    Below,
}

