// Generated by scripts/contract-snapshots.sh from sorocron_example_composite_resolver.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn set(
        env: soroban_sdk::Env,
        mode: Mode,
        resolvers: soroban_sdk::Vec<soroban_sdk::Address>,
    ) -> Result<(), Error>;
    fn mode(env: soroban_sdk::Env) -> Mode;
    fn resolvers(env: soroban_sdk::Env) -> soroban_sdk::Vec<soroban_sdk::Address>;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        mode: Mode,
        resolvers: soroban_sdk::Vec<soroban_sdk::Address>,
    );
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Mode {
    All,
    Any,
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    TooManyResolvers = 1,
    NoResolvers = 2,
}

