// Generated by scripts/contract-snapshots.sh from sorocron_example_self_extending.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn get(
        env: soroban_sdk::Env,
        key: soroban_sdk::Symbol,
    ) -> Option<soroban_sdk::Bytes>;
    fn put(
        env: soroban_sdk::Env,
        key: soroban_sdk::Symbol,
        value: soroban_sdk::Bytes,
    ) -> Result<(), Error>;
    fn extend_ttl(env: soroban_sdk::Env) -> u32;
    fn __constructor(env: soroban_sdk::Env, admin: soroban_sdk::Address);
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    TooManyKeys = 1,
}

