// Generated by scripts/contract-snapshots.sh from sorocron_example_timelock.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn queue(
        env: soroban_sdk::Env,
        target: soroban_sdk::Address,
        function: soroban_sdk::Symbol,
        args: soroban_sdk::Vec<soroban_sdk::Val>,
        eta: u64,
    ) -> Result<u64, Error>;
    fn cancel(env: soroban_sdk::Env, id: u64) -> Result<(), Error>;
    fn queued(env: soroban_sdk::Env) -> soroban_sdk::Vec<u64>;
    fn get_call(env: soroban_sdk::Env, id: u64) -> Option<Call>;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        delay: u64,
        grace: u64,
    );
    fn execute_ready(env: soroban_sdk::Env) -> u32;
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Call {
    pub args: soroban_sdk::Vec<soroban_sdk::Val>,
    pub eta: u64,
    pub function: soroban_sdk::Symbol,
    pub target: soroban_sdk::Address,
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    EtaTooSoon = 1,
    UnknownCall = 2,
}
#[soroban_sdk::contractevent(topics = ["call_expired"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct CallExpired {
    #[topic]
    pub id: u64,
}
#[soroban_sdk::contractevent(topics = ["call_executed"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct CallExecuted {
    #[topic]
    pub id: u64,
}

