// Generated by scripts/contract-snapshots.sh from sorocron_example_flag_resolver.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn set_ready(env: soroban_sdk::Env, ready: bool);
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn __constructor(env: soroban_sdk::Env, admin: soroban_sdk::Address);
}

