// Generated by scripts/contract-snapshots.sh from sorocron_example_vesting.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn get_schedule(
        env: soroban_sdk::Env,
        beneficiary: soroban_sdk::Address,
    ) -> VestingSchedule;
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        token: soroban_sdk::Address,
    );
    fn vested_amount(env: soroban_sdk::Env, beneficiary: soroban_sdk::Address) -> i128;
    fn release_vested(env: soroban_sdk::Env, beneficiary: soroban_sdk::Address) -> i128;
    fn should_run_for(env: soroban_sdk::Env, beneficiary: soroban_sdk::Address) -> bool;
    fn create_schedule(
        env: soroban_sdk::Env,
        beneficiary: soroban_sdk::Address,
        total_amount: i128,
        start_time: u64,
        cliff_duration: u64,
        total_duration: u64,
        revocable: bool,
    );
    fn releasable_amount(
        env: soroban_sdk::Env,
        beneficiary: soroban_sdk::Address,
    ) -> i128;
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct VestingSchedule {
    pub beneficiary: soroban_sdk::Address,
    pub cliff_duration: u64,
    pub released_amount: i128,
    pub revocable: bool,
    pub revoked: bool,
    pub start_time: u64,
    pub total_amount: i128,
    pub total_duration: u64,
}

