// Generated by scripts/contract-snapshots.sh from sorocron_example_dca.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn cancel(env: soroban_sdk::Env) -> i128;
    fn deposit(
        env: soroban_sdk::Env,
        from: soroban_sdk::Address,
        amount: i128,
    ) -> Result<(), DcaError>;
    fn get_plan(env: soroban_sdk::Env) -> DcaPlan;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn swap_tranche(env: soroban_sdk::Env) -> Result<i128, DcaError>;
    fn __constructor(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
        router: soroban_sdk::Address,
        sell_token: soroban_sdk::Address,
        buy_token: soroban_sdk::Address,
        amount_per_swap: i128,
        interval: u64,
        max_swaps: u32,
        min_price: i128,
    );
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct DcaPlan {
    pub active: bool,
    pub amount_per_swap: i128,
    pub buy_token: soroban_sdk::Address,
    pub executed_swaps: u32,
    pub interval: u64,
    pub max_swaps: u32,
    pub min_price: i128,
    pub next_swap_at: u64,
    pub owner: soroban_sdk::Address,
    pub router: soroban_sdk::Address,
    pub sell_token: soroban_sdk::Address,
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum DcaError {
    InvalidParameters = 1,
    PlanNotActive = 2,
    NotDueYet = 3,
    MaxSwapsReached = 4,
    InsufficientBalance = 5,
}

