// Generated by scripts/contract-snapshots.sh from sorocron_example_nft_floor_trigger.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn floor(env: soroban_sdk::Env) -> Option<i128>;
    fn trigger(env: soroban_sdk::Env) -> Trigger;
    fn should_run(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn set_trigger(env: soroban_sdk::Env, trigger: Trigger);
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        trigger: Trigger,
    );
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Trigger {
    pub collection: soroban_sdk::Address,
    pub index: soroban_sdk::Address,
    pub max_age: u64,
    pub threshold: i128,
}

