// Generated by scripts/contract-snapshots.sh from sorocron_executor.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn execute(
        env: soroban_sdk::Env,
        target: soroban_sdk::Address,
        function: soroban_sdk::Symbol,
        args: soroban_sdk::Vec<soroban_sdk::Val>,
    ) -> soroban_sdk::Val;
    fn registry(env: soroban_sdk::Env) -> soroban_sdk::Address;
    fn __constructor(env: soroban_sdk::Env, registry: soroban_sdk::Address);
}

