// Generated by scripts/contract-snapshots.sh from sorocron_registry.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn stake(
        env: soroban_sdk::Env,
        keeper: soroban_sdk::Address,
        amount: i128,
    ) -> Result<i128, Error>;
    fn config(env: soroban_sdk::Env) -> Config;
    fn is_due(env: soroban_sdk::Env, job_id: u64) -> bool;
    fn execute(
        env: soroban_sdk::Env,
        keeper: soroban_sdk::Address,
        job_id: u64,
    ) -> Result<(), Error>;
    fn get_job(env: soroban_sdk::Env, job_id: u64) -> Option<Job>;
    fn upgrade(env: soroban_sdk::Env, wasm_hash: soroban_sdk::BytesN<32>);
    fn version(env: soroban_sdk::Env) -> u32;
    fn fund_job(
        env: soroban_sdk::Env,
        from: soroban_sdk::Address,
        job_id: u64,
        amount: i128,
    ) -> Result<i128, Error>;
    fn get_jobs(env: soroban_sdk::Env, start: u64, limit: u32) -> soroban_sdk::Vec<Job>;
    fn job_count(env: soroban_sdk::Env) -> u64;
    fn cancel_job(env: soroban_sdk::Env, job_id: u64) -> Result<i128, Error>;
    fn create_job(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
        params: JobParams,
        deposit: i128,
    ) -> Result<u64, Error>;
    fn get_keeper(env: soroban_sdk::Env, keeper: soroban_sdk::Address) -> Option<Keeper>;
    fn set_paused(env: soroban_sdk::Env, paused: bool);
    fn update_job(
        env: soroban_sdk::Env,
        job_id: u64,
        update: JobUpdate,
    ) -> Result<(), Error>;
    fn create_jobs(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
        jobs: soroban_sdk::Vec<JobParams>,
        deposits: soroban_sdk::Vec<i128>,
    ) -> Result<soroban_sdk::Vec<u64>, Error>;
    fn current_fee(env: soroban_sdk::Env, job_id: u64) -> Option<i128>;
    fn accept_admin(env: soroban_sdk::Env) -> Result<(), Error>;
    fn keeper_stats(
        env: soroban_sdk::Env,
        keeper: soroban_sdk::Address,
    ) -> Option<KeeperStats>;
    fn set_executor(
        env: soroban_sdk::Env,
        executor: soroban_sdk::Address,
    ) -> Result<(), Error>;
    fn set_max_args(env: soroban_sdk::Env, max_args: u32);
    fn __constructor(
        env: soroban_sdk::Env,
        admin: soroban_sdk::Address,
        fee_token: soroban_sdk::Address,
        stake_token: soroban_sdk::Address,
        min_stake: i128,
        unbonding_period: u64,
    );
    fn execute_batch(
        env: soroban_sdk::Env,
        keeper: soroban_sdk::Address,
        job_ids: soroban_sdk::Vec<u64>,
    ) -> Result<soroban_sdk::Vec<bool>, Error>;
    fn get_job_state(env: soroban_sdk::Env, job_id: u64) -> Option<JobState>;
    fn jobs_by_owner(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
    ) -> soroban_sdk::Vec<u64>;
    fn pending_admin(env: soroban_sdk::Env) -> Option<soroban_sdk::Address>;
    fn propose_admin(env: soroban_sdk::Env, new_admin: soroban_sdk::Address);
    fn set_min_stake(env: soroban_sdk::Env, min_stake: i128) -> Result<(), Error>;
    fn active_keepers(env: soroban_sdk::Env) -> soroban_sdk::Vec<soroban_sdk::Address>;
    fn set_job_active(
        env: soroban_sdk::Env,
        job_id: u64,
        active: bool,
    ) -> Result<(), Error>;
    fn withdraw_stake(
        env: soroban_sdk::Env,
        keeper: soroban_sdk::Address,
    ) -> Result<i128, Error>;
    fn assigned_keeper(
        env: soroban_sdk::Env,
        job_id: u64,
    ) -> Option<soroban_sdk::Address>;
    fn begin_unbonding(
        env: soroban_sdk::Env,
        keeper: soroban_sdk::Address,
    ) -> Result<u64, Error>;
    fn withdraw_stakes(
        env: soroban_sdk::Env,
        keepers: soroban_sdk::Vec<soroban_sdk::Address>,
    ) -> Result<soroban_sdk::Vec<i128>, Error>;
    fn is_target_halted(env: soroban_sdk::Env, target: soroban_sdk::Address) -> bool;
    fn set_max_failures(env: soroban_sdk::Env, max_failures: u32);
    fn set_min_interval(env: soroban_sdk::Env, min_interval: u64);
    fn set_protocol_fee(
        env: soroban_sdk::Env,
        protocol_fee_bps: u32,
        treasury: Option<soroban_sdk::Address>,
    ) -> Result<(), Error>;
    fn set_target_halted(
        env: soroban_sdk::Env,
        target: soroban_sdk::Address,
        halted: bool,
    );
    fn set_keeper_windows(
        env: soroban_sdk::Env,
        grace_period: u64,
        slash_bps: u32,
    ) -> Result<(), Error>;
    fn set_unbonding_epoch(env: soroban_sdk::Env, unbonding_epoch: u64);
    fn withdraw_job_balance(
        env: soroban_sdk::Env,
        job_id: u64,
        amount: i128,
    ) -> Result<i128, Error>;
    fn cancel_admin_proposal(env: soroban_sdk::Env) -> Result<(), Error>;
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Job {
    pub active: bool,
    pub after: Option<u64>,
    pub args: soroban_sdk::Vec<soroban_sdk::Val>,
    pub balance: i128,
    pub end_at: u64,
    pub failures: u32,
    pub fee_per_run: i128,
    pub function: soroban_sdk::Symbol,
    pub id: u64,
    pub interval: u64,
    pub keepers: Option<soroban_sdk::Vec<soroban_sdk::Address>>,
    pub max_fee_per_run: i128,
    pub max_runs: u32,
    pub next_run: u64,
    pub owner: soroban_sdk::Address,
    pub resolver: Option<soroban_sdk::Address>,
    pub runs: u32,
    pub schedule: Schedule,
    pub target: soroban_sdk::Address,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Config {
    pub admin: soroban_sdk::Address,
    pub executor: Option<soroban_sdk::Address>,
    pub fee_token: soroban_sdk::Address,
    pub grace_period: u64,
    pub max_args: u32,
    pub max_failures: u32,
    pub min_interval: u64,
    pub min_stake: i128,
    pub paused: bool,
    pub protocol_fee_bps: u32,
    pub slash_bps: u32,
    pub stake_token: soroban_sdk::Address,
    pub treasury: Option<soroban_sdk::Address>,
    pub unbonding_epoch: u64,
    pub unbonding_period: u64,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Keeper {
    pub executions: u32,
    pub missed: u32,
    pub slashed: i128,
    pub stake: i128,
    pub total_lateness: u64,
    pub unbonding_at: Option<u64>,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobState {
    pub active: bool,
    pub balance: i128,
    pub failures: u32,
    pub leader_runs: u32,
    pub next_run: u64,
    pub runs: u32,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobParams {
    pub after: Option<u64>,
    pub args: soroban_sdk::Vec<soroban_sdk::Val>,
    pub end_at: u64,
    pub fee_per_run: i128,
    pub function: soroban_sdk::Symbol,
    pub interval: u64,
    pub keepers: Option<soroban_sdk::Vec<soroban_sdk::Address>>,
    pub max_fee_per_run: i128,
    pub max_runs: u32,
    pub resolver: Option<soroban_sdk::Address>,
    pub schedule: Schedule,
    pub start_at: u64,
    pub target: soroban_sdk::Address,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobUpdate {
    pub after: Option<u64>,
    pub args: soroban_sdk::Vec<soroban_sdk::Val>,
    pub end_at: u64,
    pub fee_per_run: i128,
    pub function: soroban_sdk::Symbol,
    pub interval: u64,
    pub keepers: Option<soroban_sdk::Vec<soroban_sdk::Address>>,
    pub max_fee_per_run: i128,
    pub max_runs: u32,
    pub resolver: Option<soroban_sdk::Address>,
    pub schedule: Schedule,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct KeeperStats {
    pub average_lateness: u64,
    pub eligible: bool,
    pub executions: u32,
    pub missed: u32,
    pub slashed: i128,
    pub stake: i128,
}
#[soroban_sdk::contracttype]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Schedule {
    Interval,
    Daily(u32, u32),
    Weekly(u32, u32, u32),
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    Paused = 1,
    JobNotFound = 2,
    InvalidInterval = 3,
    InvalidFee = 4,
    InvalidAmount = 5,
    ForbiddenTarget = 6,
    JobNotDue = 7,
    InsufficientJobBalance = 8,
    MaxRunsReached = 9,
    ResolverRejected = 10,
    KeeperNotFound = 11,
    InsufficientStake = 12,
    KeeperUnbonding = 13,
    UnbondingNotStarted = 14,
    UnbondingNotFinished = 15,
    ExecutorNotSet = 16,
    ExecutorAlreadySet = 17,
    NoPendingAdmin = 18,
    JobPaused = 19,
    JobExpired = 20,
    IntervalTooShort = 21,
    TooManyArgs = 22,
    TargetFailed = 23,
    InvalidBatchSize = 24,
    LengthMismatch = 25,
    KeeperNotAllowed = 26,
    NotAssignedKeeper = 27,
    TargetHalted = 28,
    InvalidCalendar = 29,
    InvalidSetting = 30,
    TooManyKeepers = 31,
    AwaitingDependency = 32,
}
#[soroban_sdk::contractevent(topics = ["upgraded"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct Upgraded {
    pub wasm_hash: soroban_sdk::BytesN<32>,
    pub previous_version: u32,
}
#[soroban_sdk::contractevent(topics = ["job_funded"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobFunded {
    #[topic]
    pub job_id: u64,
    pub from: soroban_sdk::Address,
    pub amount: i128,
    pub balance: i128,
}
#[soroban_sdk::contractevent(topics = ["paused_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct PausedSet {
    pub paused: bool,
}
#[soroban_sdk::contractevent(topics = ["job_created"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobCreated {
    #[topic]
    pub job_id: u64,
    pub owner: soroban_sdk::Address,
    pub target: soroban_sdk::Address,
    pub interval: u64,
    pub fee_per_run: i128,
    pub deposit: i128,
}
#[soroban_sdk::contractevent(topics = ["job_updated"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobUpdated {
    #[topic]
    pub job_id: u64,
    pub interval: u64,
    pub fee_per_run: i128,
    pub max_runs: u32,
    pub end_at: u64,
}
#[soroban_sdk::contractevent(topics = ["max_args_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct MaxArgsSet {
    pub max_args: u32,
}
#[soroban_sdk::contractevent(topics = ["executor_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct ExecutorSet {
    pub executor: soroban_sdk::Address,
}
#[soroban_sdk::contractevent(topics = ["job_executed"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobExecuted {
    #[topic]
    pub job_id: u64,
    #[topic]
    pub keeper: soroban_sdk::Address,
    pub success: bool,
    pub fee: i128,
    pub protocol_fee: i128,
    pub run: u32,
    pub next_run: u64,
    pub lateness: u64,
    pub failures: u32,
    pub result_hash: soroban_sdk::BytesN<32>,
}
#[soroban_sdk::contractevent(topics = ["min_stake_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct MinStakeSet {
    pub min_stake: i128,
}
#[soroban_sdk::contractevent(topics = ["admin_changed"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct AdminChanged {
    pub previous: soroban_sdk::Address,
    pub new_admin: soroban_sdk::Address,
}
#[soroban_sdk::contractevent(topics = ["job_active_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobActiveSet {
    #[topic]
    pub job_id: u64,
    pub active: bool,
}
#[soroban_sdk::contractevent(topics = ["job_cancelled"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobCancelled {
    #[topic]
    pub job_id: u64,
    pub refund: i128,
}
#[soroban_sdk::contractevent(topics = ["job_exhausted"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobExhausted {
    #[topic]
    pub job_id: u64,
    pub balance: i128,
}
#[soroban_sdk::contractevent(topics = ["job_withdrawn"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobWithdrawn {
    #[topic]
    pub job_id: u64,
    pub amount: i128,
    pub balance: i128,
}
#[soroban_sdk::contractevent(topics = ["keeper_staked"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct KeeperStaked {
    #[topic]
    pub keeper: soroban_sdk::Address,
    pub amount: i128,
    pub total: i128,
}
#[soroban_sdk::contractevent(topics = ["admin_proposed"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct AdminProposed {
    pub current: soroban_sdk::Address,
    pub proposed: soroban_sdk::Address,
}
#[soroban_sdk::contractevent(topics = ["keeper_slashed"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct KeeperSlashed {
    #[topic]
    pub keeper: soroban_sdk::Address,
    pub job_id: u64,
    pub amount: i128,
    pub remaining: i128,
    pub beneficiary: soroban_sdk::Address,
}
#[soroban_sdk::contractevent(topics = ["target_halt_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct TargetHaltSet {
    #[topic]
    pub target: soroban_sdk::Address,
    pub halted: bool,
}
#[soroban_sdk::contractevent(topics = ["job_deactivated"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct JobDeactivated {
    #[topic]
    pub job_id: u64,
    pub failures: u32,
}
#[soroban_sdk::contractevent(topics = ["max_failures_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct MaxFailuresSet {
    pub max_failures: u32,
}
#[soroban_sdk::contractevent(topics = ["min_interval_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct MinIntervalSet {
    pub min_interval: u64,
}
#[soroban_sdk::contractevent(topics = ["protocol_fee_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct ProtocolFeeSet {
    pub protocol_fee_bps: u32,
    pub treasury: Option<soroban_sdk::Address>,
}
#[soroban_sdk::contractevent(topics = ["keeper_unbonding"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct KeeperUnbonding {
    #[topic]
    pub keeper: soroban_sdk::Address,
    pub withdrawable_at: u64,
}
#[soroban_sdk::contractevent(topics = ["keeper_withdrawn"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct KeeperWithdrawn {
    #[topic]
    pub keeper: soroban_sdk::Address,
    pub amount: i128,
}
#[soroban_sdk::contractevent(topics = ["keeper_windows_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct KeeperWindowsSet {
    pub grace_period: u64,
    pub slash_bps: u32,
}
#[soroban_sdk::contractevent(topics = ["unbonding_epoch_set"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct UnbondingEpochSet {
    pub unbonding_epoch: u64,
}
#[soroban_sdk::contractevent(topics = ["admin_proposal_cancelled"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct AdminProposalCancelled {
    pub current: soroban_sdk::Address,
    pub cancelled: soroban_sdk::Address,
}

