// Generated by scripts/contract-snapshots.sh from sorocron_ttl_guardian.wasm.
// Do not edit: rebuild the contracts and rerun the script.

#[soroban_sdk::contractargs(name = "Args")]
#[soroban_sdk::contractclient(name = "Client")]
pub trait Contract {
    fn extend(
        env: soroban_sdk::Env,
        contract: soroban_sdk::Address,
        threshold: u32,
        extend_to: u32,
    ) -> Result<u32, Error>;
    fn extend_many(
        env: soroban_sdk::Env,
        contracts: soroban_sdk::Vec<soroban_sdk::Address>,
        threshold: u32,
        extend_to: u32,
    ) -> Result<soroban_sdk::Vec<u32>, Error>;
}
#[soroban_sdk::contracterror]
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub enum Error {
    InvalidTtl = 1,
    TooManyContracts = 2,
}
#[soroban_sdk::contractevent(topics = ["ttl_extended"])]
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd)]
pub struct TtlExtended {
    #[topic]
    pub contract: soroban_sdk::Address,
    pub threshold: u32,
    pub extend_to: u32,
}

