/**
 * Deploys the SoroCron contracts and examples to testnet, or to a local
 * network with STELLAR_NETWORK=local (stellar/quickstart on port 8000).
 *
 *   stellar contract build   (from the repo root)
 *   npm run deploy           (from keeper-bot/)
 *
 * If STELLAR_SECRET_KEY is unset, a fresh keypair is generated, funded with
 * Friendbot and saved to keeper-bot/.env, or to .env.<network> when a .env
 * already exists (an existing .env is never overwritten).
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  Asset,
  BASE_FEE,
  Keypair,
  Operation,
  TransactionBuilder,
  contract,
  rpc,
  xdr,
  type Transaction,
} from "@stellar/stellar-sdk";
import {
  BOT_ROOT,
  DEPLOYMENTS_FILE,
  EXPLORER,
  NETWORK,
  NETWORK_PASSPHRASE,
  RPC_URL,
  WASM_DIR,
  XLM,
  clientFor,
  ensureFunded,
  server,
  unwrap,
  type Deployment,
} from "./config.js";

const MIN_STAKE = XLM(1);
const UNBONDING_PERIOD_SECONDS = 3_600n;

async function uploadWasm(keypair: Keypair, file: string): Promise<string> {
  const path = resolve(WASM_DIR, file);
  if (!existsSync(path)) {
    throw new Error(`${path} not found. Run \`stellar contract build\` in the repo root.`);
  }
  const wasm = readFileSync(path);
  const hash = createHash("sha256").update(wasm).digest("hex");

  await submit(keypair, Operation.uploadContractWasm({ wasm }), `Uploading ${file}`);
  console.log(`  uploaded ${file} (${hash.slice(0, 12)}...)`);
  return hash;
}

/** Simulates, signs and sends a single operation, waiting for it to apply. */
async function submit(keypair: Keypair, op: xdr.Operation, what: string): Promise<void> {
  const account = await server.getAccount(keypair.publicKey());
  const tx: Transaction = new TransactionBuilder(account, { fee: BASE_FEE, networkPassphrase: NETWORK_PASSPHRASE })
    .addOperation(op)
    .setTimeout(60)
    .build();
  const prepared = await server.prepareTransaction(tx);
  prepared.sign(keypair);

  const sent = await server.sendTransaction(prepared);
  if (sent.status === "ERROR") {
    throw new Error(`${what} failed: ${JSON.stringify(sent.errorResult)}`);
  }
  const final = await server.pollTransaction(sent.hash, { attempts: 30 });
  if (final.status !== rpc.Api.GetTransactionStatus.SUCCESS) {
    throw new Error(`${what} failed with status ${final.status}`);
  }
}

/**
 * Testnet and mainnet already have the native XLM token contract; a fresh
 * local network doesn't, so deploy it before the registry needs it.
 */
async function ensureNativeToken(keypair: Keypair, feeToken: string): Promise<void> {
  try {
    await server.getContractData(feeToken, xdr.ScVal.scvLedgerKeyContractInstance(), rpc.Durability.Persistent);
    return;
  } catch {
    // Not deployed on this network yet.
  }
  console.log("Deploying the native XLM token contract...");
  await submit(keypair, Operation.createStellarAssetContract({ asset: Asset.native() }), "Deploying the XLM token");
}

async function deploy(keypair: Keypair, wasmHash: string, args: Record<string, unknown> | null): Promise<string> {
  const tx = await contract.Client.deploy(args, {
    wasmHash,
    format: "hex",
    rpcUrl: RPC_URL,
    allowHttp: RPC_URL.startsWith("http://"),
    networkPassphrase: NETWORK_PASSPHRASE,
    publicKey: keypair.publicKey(),
    ...contract.basicNodeSigner(keypair, NETWORK_PASSPHRASE),
  });
  const { result } = await tx.signAndSend();
  return result.options.contractId;
}

/**
 * Saves the deployment's settings to keeper-bot/.env, unless one already
 * exists: an existing .env (perhaps holding a key for another network) is
 * never overwritten, and the settings go to .env.<network> instead.
 */
function writeEnv(secret: string, registry: string): string {
  const lines = [
    "# Generated by `npm run deploy`. Never commit this file.",
    `STELLAR_SECRET_KEY=${secret}`,
    `STELLAR_NETWORK=${NETWORK}`,
    `STELLAR_RPC_URL=${RPC_URL}`,
    `SOROCRON_CONTRACT_ID=${registry}`,
    "POLL_INTERVAL_MS=10000",
    "",
  ];
  const envPath = resolve(BOT_ROOT, ".env");
  const path = existsSync(envPath) ? resolve(BOT_ROOT, `.env.${NETWORK}`) : envPath;
  writeFileSync(path, lines.join("\n"));
  return path;
}

async function main() {
  if (NETWORK === "mainnet") {
    throw new Error("This script deploys to testnet or a local network, not mainnet.");
  }

  const keypair = process.env.STELLAR_SECRET_KEY
    ? Keypair.fromSecret(process.env.STELLAR_SECRET_KEY)
    : Keypair.random();
  await ensureFunded(keypair);
  const admin = keypair.publicKey();
  const feeToken = Asset.native().contractId(NETWORK_PASSPHRASE);
  await ensureNativeToken(keypair, feeToken);

  console.log(`Deploying SoroCron to ${NETWORK} as ${admin}`);
  console.log("Uploading WASM...");
  const registryHash = await uploadWasm(keypair, "sorocron_registry.wasm");
  const executorHash = await uploadWasm(keypair, "sorocron_executor.wasm");
  const guardianHash = await uploadWasm(keypair, "sorocron_ttl_guardian.wasm");
  const counterHash = await uploadWasm(keypair, "sorocron_example_counter.wasm");
  const resolverHash = await uploadWasm(keypair, "sorocron_example_flag_resolver.wasm");

  console.log("Deploying contracts...");
  const registry = await deploy(keypair, registryHash, {
    admin,
    fee_token: feeToken,
    stake_token: feeToken,
    min_stake: MIN_STAKE,
    unbonding_period: UNBONDING_PERIOD_SECONDS,
  });
  console.log(`  registry       ${registry}`);

  const executor = await deploy(keypair, executorHash, { registry });
  console.log(`  executor       ${executor}`);
  const registryClient = await clientFor(registry, keypair);
  unwrap((await (await registryClient.set_executor({ executor })).signAndSend()).result);
  console.log("  executor connected to registry");

  const ttlGuardian = await deploy(keypair, guardianHash, null);
  console.log(`  ttl-guardian   ${ttlGuardian}`);
  const counter = await deploy(keypair, counterHash, null);
  console.log(`  counter        ${counter}`);
  const flagResolver = await deploy(keypair, resolverHash, { admin });
  console.log(`  flag-resolver  ${flagResolver}`);

  const deployment: Deployment = {
    network: NETWORK,
    registry,
    executor,
    ttlGuardian,
    counter,
    flagResolver,
    feeToken,
    admin,
    deployedAt: new Date().toISOString(),
  };
  mkdirSync(dirname(DEPLOYMENTS_FILE), { recursive: true });
  writeFileSync(DEPLOYMENTS_FILE, JSON.stringify(deployment, null, 2) + "\n");
  const envFile = writeEnv(keypair.secret(), registry);

  console.log(`\nSaved ${DEPLOYMENTS_FILE}`);
  if (!envFile.endsWith(".env")) {
    console.log(`keeper-bot/.env already exists and was left alone; this deployment's settings are in ${envFile}.`);
  }
  console.log(`Explorer: ${EXPLORER}/contract/${registry}`);
  console.log("Next: npm run demo");
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
