#!/usr/bin/env bash
# Snapshots every built contract's public interface and WASM size.
#
#   scripts/contract-snapshots.sh            rewrite the snapshots
#   scripts/contract-snapshots.sh --check    fail if an interface changed
#   scripts/contract-snapshots.sh --sizes    print a Markdown size table
#
# Run `stellar contract build` first. Interfaces (functions, types, errors
# and events, as Rust) go to contracts/interfaces/<contract>.rs and sizes to
# contracts/wasm-sizes.txt. Changing an interface is fine, but it should be
# deliberate: rerun this script and commit the result so the diff shows up in
# review.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
wasm_dir="$root/target/wasm32v1-none/release"
interfaces="$root/contracts/interfaces"
sizes="$root/contracts/wasm-sizes.txt"
budget=60000

shopt -s nullglob
wasms=("$wasm_dir"/sorocron_*.wasm)
if [ ${#wasms[@]} -eq 0 ]; then
  echo "No WASM in $wasm_dir; run 'stellar contract build' first." >&2
  exit 1
fi

name() { basename "$1" .wasm | sed 's/^sorocron_//'; }

interface() {
  stellar --quiet contract info interface --wasm "$1" --output rust | tr -d '\r'
}

file_size() { wc -c <"$1" | tr -d ' '; }

case "${1:-}" in
  "")
    mkdir -p "$interfaces"
    rm -f "$interfaces"/*.rs
    : >"$sizes"
    for wasm in "${wasms[@]}"; do
      n="$(name "$wasm")"
      {
        echo "// Generated by scripts/contract-snapshots.sh from $(basename "$wasm")."
        echo "// Do not edit: rebuild the contracts and rerun the script."
        echo
        interface "$wasm"
      } >"$interfaces/$n.rs"
      echo "$n $(file_size "$wasm")" >>"$sizes"
    done
    echo "Wrote ${#wasms[@]} interfaces to contracts/interfaces and sizes to contracts/wasm-sizes.txt."
    ;;

  --check)
    changed=0
    for wasm in "${wasms[@]}"; do
      n="$(name "$wasm")"
      snapshot="$interfaces/$n.rs"
      if [ ! -f "$snapshot" ]; then
        echo "::error::$n has no interface snapshot (new contract?)."
        changed=1
        continue
      fi
      if ! diff -u --label "snapshot: $n" --label "built: $n" \
        <(tail -n +4 "$snapshot" | tr -d '\r') <(interface "$wasm"); then
        echo "::error file=contracts/interfaces/$n.rs::The $n interface changed."
        changed=1
      fi
    done
    for snapshot in "$interfaces"/*.rs; do
      n="$(basename "$snapshot" .rs)"
      if [ ! -f "$wasm_dir/sorocron_$n.wasm" ]; then
        echo "::error file=contracts/interfaces/$n.rs::$n has a snapshot but no longer builds."
        changed=1
      fi
    done
    if [ "$changed" -ne 0 ]; then
      cat <<'EOF'

A contract's public interface (functions, types, error codes or events)
differs from contracts/interfaces. Keepers, the SDK and the app depend on it,
so a change here can break them. If the change is intended, run

    stellar contract build && scripts/contract-snapshots.sh

and commit the updated snapshots so reviewers see the diff.
EOF
      exit 1
    fi
    echo "All ${#wasms[@]} contract interfaces match their snapshots."
    ;;

  --sizes)
    echo "| Contract | Size (bytes) | Recorded | Change | Budget used |"
    echo "| --- | ---: | ---: | ---: | ---: |"
    for wasm in "${wasms[@]}"; do
      n="$(name "$wasm")"
      size="$(file_size "$wasm")"
      recorded="$(awk -v n="$n" '$1 == n { print $2 }' "$sizes" 2>/dev/null || true)"
      if [ -z "$recorded" ]; then
        recorded="-"
        change="new"
      else
        delta=$((size - recorded))
        if [ "$delta" -gt 0 ]; then change="+$delta"; else change="$delta"; fi
      fi
      used=$(awk -v s="$size" -v b="$budget" 'BEGIN { printf "%.1f%%", 100 * s / b }')
      echo "| \`$n\` | $size | $recorded | $change | $used |"
    done
    echo
    echo "Budget: $budget bytes per contract (Soroban's limit is 64 KB)."
    echo "\"Recorded\" is contracts/wasm-sizes.txt; rerun scripts/contract-snapshots.sh to update it."
    ;;

  *)
    echo "usage: $0 [--check | --sizes]" >&2
    exit 2
    ;;
esac
